name: CI/CD - Push to develop

on:
  push:
    branches:
      - develop

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '12'
      - run: node prepare-env-deploy.js
        env:
          FIREBASE_DETAILS: ${{ secrets.FIREBASE_DETAILS }}
      - name: Build
        run: |
          npm install
          npm run build
      - name: Install Firebase Tools
        run: sudo npm install -g firebase-tools@9.23.3
      - name: Firebase Deploy
        run: firebase deploy --only hosting --token ${{ secrets.FIREBASE_TOKEN }}
